### ISSUE TITLE
Tables do not show data

### ISSUE THREAD

**Issue by jvv-trackunit** [axiomhq/axiom-grafana#81]
While using the plugin version 0.3.0, I performed a summary query and visualized it in a table panel.

After upgrading the Axiom datasource plugin to version 0.6.0, the table is now empty: 
<img width="1794" alt="Screenshot 2024-12-11 at 11 37 00" src="https://github.com/user-attachments/assets/850ef2a8-86de-4ab8-807b-4043adb3a0d6">

According to the query inspector, the query returned no results. The same dashboard does load results when using the plugin version 0.3.0.

Dashboard containing table that doesn't work:
[table-not-showing-data.json](https://github.com/user-attachments/files/18094671/table-not-showing-data.json)

Output from query inspector:
[query-inspector.json](https://github.com/user-attachments/files/18094661/query-inspector.json)

Versions used:
Grafana v11.4.0 (b58701869e)
Firefox 133.0
Mac OS: 15.1.1

**Comment by dasfmi** [comment]
hi @jvv-trackunit, thanks for reporting this. I was able to reproduce. 

The underlying issue was the plugin expected Timespan fields to be float64 but they query result returns a string. I have updated the plugin to expect a string and that fixed it. I will submit for a new release on the Grafana marketplace and will notify you once its reviewed and approved.

**Comment by dasfmi** [comment]
@jvv-trackunit new version is released to the Grafana marketplace, please give it a try and let me if know if you still face the issue.

**Comment by jvv-trackunit** [comment]
Hi @dasfmi 

The tables populate after upgrading to version 0.6.1. Thanks for the fix.
